name: Node.js CI

on:
  push:
    branches: [ "branch1" ]
  pull_request:
    branches: [ "branch1" ]

jobs:
  build:
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build

    # - name: Install Chrome
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y wget unzip
    #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #     sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

    # - name: Test
    #   run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

    # - name: Cypress run
    #   uses: cypress-io/github-action@v2
    #   with:
    #     build: npm run build
    #     start: npm start   

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: venkatesh.k@innoart.io
        password: Venki123#

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: venki098/sample:1.0.3

    - name: Image digest
      run: echo "Docker image built and pushed successfully"
